In [2]:
import pandas as pd

In [7]:
df=pd.read_csv(r'Masai_notes_Data_preperation_march30\used_cars_messy.csv')

In [9]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0

In [11]:
df.describe()

,Unnamed: 0,vehicle_age,engine,max_power,seats,selling_price
count,15661.000000,15661.000000,13792.000000,14862.000000,15218.000000,1.550300e+04
mean,9808.189643,6.036843,1480.489342,100.513582,5.324418,1.032764e+06
std,5642.981540,3.015072,511.446057,42.854632,0.805993,1.607380e+07
min,0.000000,0.000000,793.000000,38.400000,0.000000,5.000000e+02
25%,4901.000000,4.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,9858.000000,6.000000,1248.000000,88.500000,5.000000,5.550000e+05
75%,14666.000000,8.000000,1582.000000,117.300000,5.000000,8.250000e+05
max,19543.000000,29.000000,6592.000000,626.000000,9.000000,1.000000e+09

In [14]:
df.shape

(15661, 14)

In [25]:
df.dtypes

Unnamed: 0             int64
car_name                 str
brand                    str
model                    str
vehicle_age            int64
km_driven            float64
seller_type              str
fuel_type                str
transmission_type        str
mileage              float64
engine               float64
max_power            float64
seats                float64
selling_price        float64
dtype: object

In [20]:
df['km_driven'] = df['km_driven'].astype(str).str.strip()

In [23]:
df['mileage'] = (
    df['mileage']
    .astype(str)
    .str.replace(r'[^0-9.]', '', regex=True)
    .astype(float)
)

In [27]:
df['km_driven']=df['km_driven'].astype(str).str.replace(r'[^0-9.]', '',regex=True).astype(float)

In [39]:
import pandas as pd

pd.Series(df['km_driven'].unique()).value_counts()

67647.0     1
52000.0     1
48959.0     1
82000.0     1
34000.0     1
           ..
43001.0     1
43200.0     1
39337.0     1
66850.0     1
127731.0    1
Name: count, Length: 3738, dtype: int64